
services:
  postgres:
    image: postgres:16
    container_name: skillshare_db 
    environment:
      POSTGRES_DB: skillshare
      POSTGRES_USER: skillshare
      POSTGRES_PASSWORD: skillshare
    ports:
      - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
  # - ./data/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql # Script SQL exécuté à l'initialisation
    
    restart: unless-stopped # Redémarre le conteneur sauf si on l'arrête manuellement

  backend:
    build: ./backend
    container_name: skillshare_back
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app 
    restart: unless-stopped 

  #frontend:
    #build: . # Construit l'image à partir du Dockerfile à la racine
    #container_name: skillshare_front
    #ports:
      #- "8000:8000" # Expose le port 8000 du conteneur sur le port 8000 de la machine hôte
    #env_file:
      #- .env # Charge les variables d'environnement depuis le fichier .env
    #depends_on:
      #- postgres # Démarre le service db avant l'app
    #volumes:
      #- .:/frontend # Monte le dossier du projet dans le conteneur pour le développement
    #restart: unless-stopped # Redémarre le conteneur sauf si on l'arrête manuellement

volumes: 
  db_data:
