services:
  postgres:
    image: postgres:16
    container_name: skillshare_db
    environment:
      POSTGRES_DB: skillshare
      POSTGRES_USER: skillshare
      POSTGRES_PASSWORD: skillshare
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/data/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./backend/seeds/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      platforms:
        - linux/amd64
        - linux/arm64
    command: sh -c "until nc -z postgres 5432; do echo 'Waiting for Postgres...'; sleep 2; done; npm run dev"
    container_name: skillshare_back
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: skillshare_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  db_data: